development:
  secret_key_base: 3ef52d42bd06b79b7df0f9094bc04b50e0243ba0cbc79f88cbdc194aa72381898d4fae9631492c0cdfa9b47914eb5a4c9d0fa89a4dc662fec230d82429fc68fa
  telegram:
    bot:
      token: <%= ENV['TG_BOT_TOKEN'] %>
      username: <%= ENV['TG_BOT_NAME'] %>

test:
  secret_key_base: fd0070d6396fd9760c6dedf632ba53f0e5f67e61acb1c444c5f7817419a107901cb421b581142b1f17efaf4291d578205415cb805667b924f9b72ba1967ab9c7
  telegram:
    bot:
      token: <%= ENV['TG_BOT_TOKEN'] %>
      username: <%= ENV['TG_BOT_NAME'] %>

staging:
  secret_key_base: ENV['STAG_SECRET_KEY_BASE']
  telegram:
    bot:
      token: <%= ENV['TG_BOT_TOKEN'] %>
      username: <%= ENV['TG_BOT_NAME'] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram:
    bot:
      token: <%= ENV['TG_BOT_TOKEN'] %>
      username: <%= ENV['TG_BOT_NAME'] %>
